name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
    - name: prepare
      run: bash ci/tests-environment.sh
    - name: build
      run: bash ci/tests-ci.sh
    - uses: actions/upload-artifact@v3
      with:
        name: Executable artifacts
        path: /tmp/result
